language:
- python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: WuAdJEUYL9GGjhUJu/mxhs0fQgKC/vr4T0k9JZFCzM2AmpP00BPbdBjWM4OFO8+GwQW4ov/zkR8nTLwoFZmOOQlBd5xdaAD2uqD2mdmko0OKqhCXS8YvziJNaQewNPe9/qrPWnYcFLI/ZaTfr3js2zAE3n6QrqUnrs2XCgeVhrk=
  app: tranquil-refuge-6545
  on:
    branch: master
    repo: SimoCi/flasktaskr-project
